### ISSUE TITLE
Output error

### ISSUE THREAD

**Issue by Welsh-Boogie** [brunomuratore/GoogleHashCode#4]
Hi, there is an error in either compiling or putting directory properly for files, could you share the output files for this and last year? thanks

**Comment by Welsh-Boogie** [comment]
If u could attach a media fire link it would be helpful. ill try searching a tutorial for directories because the error is persistent even with a fresh code.

**Comment by brunomuratore** [comment]
@Welsh-Boogie Hey, I believe you can just create an empty "output" directory and it should work.

**Comment by Welsh-Boogie** [comment]
> @Welsh-Boogie Hey, I believe you can just create an empty "output" directory and it should work.

tried it, however it doesn't work, I even reinstalled libs

**Comment by Welsh-Boogie** [comment]
its not error on your side, its my side error

**Comment by Welsh-Boogie** [comment]
@brunomuratore

**Comment by Welsh-Boogie** [comment]
@brunomuratore is it possible for u to drop the output? it would really be nice, thanks.

**Comment by brunomuratore** [comment]
I am not sure what you are trying to do when you get the error, or what is the error. Also not sure what you mean by drop the output.

Is this error while compiling? How are you trying to compile it? Can you post the full output of the error?

**Comment by Welsh-Boogie** [comment]
> I am not sure what you are trying to do when you get the error, or what is the error. Also not sure what you mean by drop the output.
> 
> Is this error while compiling? How are you trying to compile it? Can you post the full output of the error?

its can error in vscode its not while running it, its coming for other programs too, using this https://code.visualstudio.com/docs/languages/csharp rn. the error is just it opens another page. my friends say my libs are messed up

and when I was asking for output meant the .out so I could try decontruct them.
